# Site settings
title:       Jakub Węgrzynowski
email:       your_email@example.com
author:      Jakub Florian
description: "Miejsce, w którym przechowuję swoje notatki prawnicze. Mam nadzieję, że będą one pomocne dla innych studentów prawa."
baseurl:     "/notatki-prawo"
url:         "https://jakub-florian.github.io"
date_format: "%b %-d, %Y"
header_pages:
 - spis.md

avatar: "/assets/img/awatar.png"

# Optional features
animated:             false
show_related_posts:   false
author: "Jakub Węgrzynowski"
avatar: "/assets/img/awatar.png"   # ustaw ścieżkę do Twojego avatara
bio: "student prawa WPiA UŁ · copywriter ·"
show_post_footers:    true
show_social_icons:    false
enable_mathjax: false
extended_fonts: false
enable_anchorjs: false
# Preview image for social media aka og:image and twitter:image
post_preview_image: false

# Social icons
github_username: "Jakub-Florian"

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - screenshot.png
  - vendor
